update all dependencies to the latest major versions
I had to stick to node 16 instead of 18 since that's the latest version
supported by github actions.

This was required due to this build error:
ncc: Version 0.28.6
ncc: Compiling file index.js
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at hashOf (/home/runner/work/actions-zephyr-sdk/actions-zephyr-sdk/node_modules/@vercel/ncc/dist/ncc/index.js.cache.js:37:1814625)
    at ncc (/home/runner/work/actions-zephyr-sdk/actions-zephyr-sdk/node_modules/@vercel/ncc/dist/ncc/index.js.cache.js:37:1818842)
    at runCmd (/home/runner/work/actions-zephyr-sdk/actions-zephyr-sdk/node_modules/@vercel/ncc/dist/ncc/cli.js.cache.js:1:51862)
    at 819 (/home/runner/work/actions-zephyr-sdk/actions-zephyr-sdk/node_modules/@vercel/ncc/dist/ncc/cli.js.cache.js:1:48659)
    at __webpack_require__ (/home/runner/work/actions-zephyr-sdk/actions-zephyr-sdk/node_modules/@vercel/ncc/dist/ncc/cli.js.cache.js:1:55378)
    at /home/runner/work/actions-zephyr-sdk/actions-zephyr-sdk/node_modules/@vercel/ncc/dist/ncc/cli.js.cache.js:1:55590
    at /home/runner/work/actions-zephyr-sdk/actions-zephyr-sdk/node_modules/@vercel/ncc/dist/ncc/cli.js.cache.js:1:55651
    at Object.<anonymous> (/home/runner/work/actions-zephyr-sdk/actions-zephyr-sdk/node_modules/@vercel/ncc/dist/ncc/cli.js:8:28) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

There also were 4 dependabot alerts, so it was a good idea anyway.
(2, 3, 4, 6).